#ifndef TIMELINETREECONFIG_H
#define TIMELINETREECONFIG_H

#define FRAME_HALF_WIDTH 4
#define FRAME_WIDTH (FRAME_HALF_WIDTH*2)
#define FRAME_HALF_HEIGHT 10
#define FRAME_HEIGHT (FRAME_HALF_HEIGHT*2)

#define MARKER_HALF_WIDTH 2
#define MARKER_HALF_HEIGHT 5
#define MARKER_WIDTH (MARKER_HALF_WIDTH*2)
#define MARKER_HEIGHT (MARKER_HALF_HEIGHT*2)
#define BAR_MARGIN 3

#endif // TIMELINETREECONFIG_H
